export const categories = ["All Programme", "Mathematics", "English", "Programming", "Science"];
export const courses = [
  {
    category: "Mathematics",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "10th June 2025",
    title: "Mathematics",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "12",
    mode: "Online & Offline Available",
    timings: "5:00 PM – 8:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "English",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "8th June 2025",
    title: "English Language",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "1 to 12",
    mode: "Near You & Online",
    timings: "3:00 PM – 6:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Programming",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "15th June 2025",
    title: "Computer Basics to Programming",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "9 to Degree",
    mode: "Home & Online Tuition",
    timings: "Weekdays – 6:00 PM to 9:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Mathematics",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "10th June 2025",
    title: "Mathematics",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "12",
    mode: "Online & Offline Available",
    timings: "5:00 PM – 8:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "English",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "8th June 2025",
    title: "English Language",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "1 to 12",
    mode: "Near You & Online",
    timings: "3:00 PM – 6:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Programming",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "15th June 2025",
    title: "Computer Basics to Programming",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "9 to Degree",
    mode: "Home & Online Tuition",
    timings: "Weekdays – 6:00 PM to 9:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Mathematics",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "10th June 2025",
    title: "Mathematics",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "12",
    mode: "Online & Offline Available",
    timings: "5:00 PM – 8:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "English",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "8th June 2025",
    title: "English Language",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "1 to 12",
    mode: "Near You & Online",
    timings: "3:00 PM – 6:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Programming",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "15th June 2025",
    title: "Computer Basics to Programming",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "9 to Degree",
    mode: "Home & Online Tuition",
    timings: "Weekdays – 6:00 PM to 9:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Mathematics",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "10th June 2025",
    title: "Mathematics",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "12",
    mode: "Online & Offline Available",
    timings: "5:00 PM – 8:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "English",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "8th June 2025",
    title: "English Language",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "1 to 12",
    mode: "Near You & Online",
    timings: "3:00 PM – 6:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Programming",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "15th June 2025",
    title: "Computer Basics to Programming",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "9 to Degree",
    mode: "Home & Online Tuition",
    timings: "Weekdays – 6:00 PM to 9:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Mathematics",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "10th June 2025",
    title: "Mathematics",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "12",
    mode: "Online & Offline Available",
    timings: "5:00 PM – 8:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "English",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "8th June 2025",
    title: "English Language",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "1 to 12",
    mode: "Near You & Online",
    timings: "3:00 PM – 6:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Programming",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "15th June 2025",
    title: "Computer Basics to Programming",
    description: "Master algebra, geometry, and more with expert local tutors.",
    classes: "9 to Degree",
    mode: "Home & Online Tuition",
    timings: "Weekdays – 6:00 PM to 9:00 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  {
    category: "Science",
    imageUrl: "/images/home/courses/course.png",
    studentCount: 40,
    startDate: "12th June 2025",
    title: "Science",
    description: "Understand Physics, Chemistry & Biology with real-world examples.",
    classes: "6 to 10",
    mode: "Online Only",
    timings: "4:30 PM – 7:30 PM",
    price: 1380,
    originalPrice: 2500,
  },
  
];